# https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# Avatar image url
avatar: https://cdn-image-argvchs.netlify.app/avatar.jpg

# Home page head info block
head_block_enable: true

# Home page head background style
home_background: https://cdn-image-argvchs.netlify.app/home.jpg

# WARNING! vfonts (variable fonts) feature is EXPERIMENTAL
# MDN: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
vfonts_enable: true

# ParticleX theme icon is adopts the font awesome 6
# Link: https://fontawesome.com/search/

# Main menu navigation
menu:
    home:
        name: house
        theme: solid
        src: /
    about:
        name: id-card
        theme: solid
        src: /about
    archives:
        name: box-archive
        theme: solid
        src: /archives
    categories:
        name: bookmark
        theme: solid
        src: /categories
    tags:
        name: tags
        theme: solid
        src: /tags
    # Example:
    # <name>:
    #     name: <icon-name>
    #     theme: <icon-theme>
    #     src: <link-url>

# Side info card
card:
    enable: true
    description: ["Here's an Argvchs..."] # You can add more
    icon_links:
        github:
            name: github
            theme: brands
            link: https://github.com/argvchs
        qq:
            name: qq
            theme: brands
            link: http://wpa.qq.com/msgrd?v=3&uin=3364555156&site=qq&menu=true
        twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/argvchs
        email:
            name: envelope
            theme: solid
            link: mailto:argvchs@outlook.com
        # Example:
        # <name>:
        #    name: <icon-name>
        #    theme: <icon-theme>
        #    link: <link-url>
    friend_links:
        []
        # Example:
        # <name>: <link-url>

# Footer info
footer:
    since: 20xx
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:
        link:

search:
    enable: true
    path: # Default: search.json

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: true
    clientID: 170844d595d9facb0be0 # Default ClientID
    clientSecret: 21b990860bd70f9ac33d06f06d3232e82c464a3a # Default ClientSecret
    repo: gitalk-comments # The name of repository of store comments
    owner: argvchs # GitHub repo owner
    admin: argvchs # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.
    proxy: https://cors-anywhere-argvchs.herokuapp.com/https://github.com/login/oauth/access_token  # CORS proxy
    sites: # Sites
        argvchs.github.io:
            clientID: 170844d595d9facb0be0
            clientSecret: 21b990860bd70f9ac33d06f06d3232e82c464a3a
        argvchs.netlify.app:
            clientID: 10e5540a489691cc9d41
            clientSecret: b85c16d808150287a7ba8215fa9021470783909d
        argvchs.vercel.app:
            clientID: cc3e39819ab1db56cbcc
            clientSecret: 31e556e8e6275f47e1c847c368b654e7f26544b1
        # Example:
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>

# Giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang: zh-CN
    crossorigin: anonymous

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: # Waline server address url, you should set this to your own link
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
        {}
        # Example:
        # placeholder: Leave a comment
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.0.1/weibo
        - https://unpkg.com/@waline/emojis@1.0.1/alus
        - https://unpkg.com/@waline/emojis@1.0.1/bilibili
        - https://unpkg.com/@waline/emojis@1.0.1/qq
        - https://unpkg.com/@waline/emojis@1.0.1/tieba
        - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: zh-CN # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page
